In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np
import pandas as pd

import ast

pd.set_option('display.max_columns', None) # show all columns

----------

Vuelo Pasajeros

In [ ]:
dfVP = pd.read_csv('/content/drive/MyDrive/NoCountry|S14-27/TablasTransformadas/SalidasInternacionalesPasajerosUSA.csv')

In [ ]:
dfVP.rename({'AÃ±o':'Anio'},axis=1, inplace=True)

In [ ]:
# eliminar registros ya q aeropuerto no existe
dfVP.drop(index=dfVP[dfVP['AeropuertoO']=='ZZZ'].index, axis=1, inplace=True)

In [ ]:
# contar cantidad de nulos por cada variable
dfVP.isna().sum()

Anio                  0
Mes                   0
IDAeropuertoO         0
AeropuertoO           0
IDAeropuertoD         0
AeropuertoD           0
IDAerolinea           0
Aerolinea          3516
TablaOrigen           0
VPasajerosC          21
VPasajerosP          21
AsientosC        261588
AsientosP        261588
PasajerosC       284261
PasajerosP       284261
dtype: int64

In [ ]:
# imputar valores nulos
dfVP['Aerolinea'].fillna(value='NA', inplace=True)

In [ ]:
dfVP.IDAeropuertoO = dfVP.IDAeropuertoO.astype('string')
dfVP.IDAeropuertoD = dfVP.IDAeropuertoD.astype('string')
dfVP.IDAerolinea = dfVP.IDAerolinea.astype('string')

In [ ]:
dfVP.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1050295 entries, 0 to 1051312
Data columns (total 15 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Anio           1050295 non-null  int64
 1   Mes            1050295 non-null  int64
 2   IDAeropuertoO  1050295 non-null  string
 3   AeropuertoO    1050295 non-null  object
 4   IDAeropuertoD  1050295 non-null  string
 5   AeropuertoD    1050295 non-null  object
 6   IDAerolinea    1050295 non-null  string
 7   Aerolinea      1050295 non-null  object
 8   TablaOrigen    1050295 non-null  object
 9   VPasajerosC    1050274 non-null  float64
 10  VPasajerosP    1050274 non-null  float64
 11  AsientosC      788707 non-null   float64
 12  AsientosP      788707 non-null   float64
 13  PasajerosC     766034 non-null   float64
 14  PasajerosP     766034 non-null   float64
dtypes: float64(6), int64(2), object(4), string(3)
memory usage: 128.2+ MB

In [ ]:
dfVP.head()

,Anio,Mes,IDAeropuertoO,AeropuertoO,IDAeropuertoD,AeropuertoD,IDAerolinea,Aerolinea,TablaOrigen,VPasajerosC,VPasajerosP,AsientosC,AsientosP,PasajerosC,PasajerosP
0,2006,5,12016,GUM,13162,MAJ,20177,PFQ,['VueloPasajeros'],0.0,10.0,NaN,NaN,NaN,NaN
1,2009,4,10397,ATL,16321,ZRH,19790,DL,"['VueloPasajeros', 'Asientos', 'Pasajeros']",54.0,0.0,11661.0,0.0,8496.0,0.0
2,2003,5,10299,ANC,13856,OKO,20007,5Y,['VueloPasajeros'],0.0,15.0,NaN,NaN,NaN,NaN
3,2005,2,11057,CLT,14849,SKB,20355,US,"['VueloPasajeros', 'Asientos', 'Pasajeros']",8.0,0.0,952.0,0.0,733.0,0.0
4,2004,1,12478,JFK,11625,EZE,19535,AR,"['VueloPasajeros', 'Asientos', 'Pasajeros']",30.0,0.0,7410.0,0.0,5977.0,0.0

----------

Vuelo Pasajeros Carga

In [ ]:
dfVPC = pd.read_csv('/content/drive/MyDrive/NoCountry|S14-27/TablasTransformadas/SalidasInternacionalesUSA.csv')

In [ ]:
dfVPC.rename({'AÃ±o':'Anio'},axis=1, inplace=True)

In [ ]:
# eliminar registros ya q aeropuerto no existe
dfVPC.drop(index=dfVPC[dfVPC['AeropuertoO']=='ZZZ'].index, axis=1, inplace=True)

In [ ]:
# contar cantidad de nulos por cada variable
dfVPC.isna().sum()

Anio                  0
Mes                   0
IDAeropuertoO         0
AeropuertoO           0
IDAeropuertoD         0
AeropuertoD           0
IDAerolinea           0
Aerolinea          3516
TablaOrigen           0
VPasajerosC          26
VPasajerosP          26
VCargaC          424882
VCargaP          424882
AsientosC        261593
AsientosP        261593
PasajerosC       284266
PasajerosP       284266
dtype: int64

In [ ]:
# imputar valores nulos
dfVPC['Aerolinea'].fillna(value='NA', inplace=True)

In [ ]:
dfVPC.IDAeropuertoO = dfVPC.IDAeropuertoO.astype('string')
dfVPC.IDAeropuertoD = dfVPC.IDAeropuertoD.astype('string')
dfVPC.IDAerolinea = dfVPC.IDAerolinea.astype('string')

In [ ]:
dfVPC.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1050300 entries, 0 to 1051317
Data columns (total 17 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   Anio           1050300 non-null  int64
 1   Mes            1050300 non-null  int64
 2   IDAeropuertoO  1050300 non-null  string
 3   AeropuertoO    1050300 non-null  object
 4   IDAeropuertoD  1050300 non-null  string
 5   AeropuertoD    1050300 non-null  object
 6   IDAerolinea    1050300 non-null  string
 7   Aerolinea      1050300 non-null  object
 8   TablaOrigen    1050300 non-null  object
 9   VPasajerosC    1050274 non-null  float64
 10  VPasajerosP    1050274 non-null  float64
 11  VCargaC        625418 non-null   float64
 12  VCargaP        625418 non-null   float64
 13  AsientosC      788707 non-null   float64
 14  AsientosP      788707 non-null   float64
 15  PasajerosC     766034 non-null   float64
 16  PasajerosP     766034 non-null   float64
dtypes: float64(8), int64(2), object(4), string(3)
memory usage: 144.2+ MB

In [ ]:
dfVPC.head()

,Anio,Mes,IDAeropuertoO,AeropuertoO,IDAeropuertoD,AeropuertoD,IDAerolinea,Aerolinea,TablaOrigen,VPasajerosC,VPasajerosP,VCargaC,VCargaP,AsientosC,AsientosP,PasajerosC,PasajerosP
0,2006,5,12016,GUM,13162,MAJ,20177,PFQ,"['VueloPasajeros', 'VueloCarga']",0.0,10.0,0.0,16.0,NaN,NaN,NaN,NaN
1,2009,4,10397,ATL,16321,ZRH,19790,DL,"['VueloPasajeros', 'VueloCarga', 'Asientos', '...",54.0,0.0,280.0,0.0,11661.0,0.0,8496.0,0.0
2,2003,5,10299,ANC,13856,OKO,20007,5Y,"['VueloPasajeros', 'VueloCarga']",0.0,15.0,0.0,762.0,NaN,NaN,NaN,NaN
3,2005,2,11057,CLT,14849,SKB,20355,US,"['VueloPasajeros', 'Asientos', 'Pasajeros']",8.0,0.0,NaN,NaN,952.0,0.0,733.0,0.0
4,2004,1,12478,JFK,11625,EZE,19535,AR,"['VueloPasajeros', 'VueloCarga', 'Asientos', '...",30.0,0.0,181.0,0.0,7410.0,0.0,5977.0,0.0

--------------------

Vuelo Carga

In [ ]:
dfVC = pd.read_csv('/content/drive/MyDrive/NoCountry|S14-27/TablasTransformadas/VueloCarga.csv')

In [ ]:
dfVC.rename({'AÃ±o':'Anio'},axis=1, inplace=True)

In [ ]:
# eliminar registros ya q aeropuerto no existe
dfVC.drop(index=dfVC[dfVC['AeropuertoO']=='ZZZ'].index, axis=1, inplace=True)

In [ ]:
# contar cantidad de nulos por cada variable
dfVC.isna().sum()

Anio               0
Mes                0
IDAeropuertoO      0
AeropuertoO        0
IDAeropuertoD      0
AeropuertoD        0
IDAerolinea        0
Aerolinea        106
TipoAerolinea      0
TablaOrigen        0
VCargaC            0
VCargaP            0
dtype: int64

In [ ]:
# imputar valores nulos
dfVC['Aerolinea'].fillna(value='NA', inplace=True)

In [ ]:
dfVC = dfVC[['Anio','Mes','IDAeropuertoO','AeropuertoO','IDAeropuertoD','AeropuertoD','IDAerolinea','Aerolinea','VCargaC','VCargaP']]

In [ ]:
dfVC.IDAeropuertoO = dfVC.IDAeropuertoO.astype('string')
dfVC.IDAeropuertoD = dfVC.IDAeropuertoD.astype('string')
dfVC.IDAerolinea = dfVC.IDAerolinea.astype('string')

In [ ]:
dfVC.info()

<class 'pandas.core.frame.DataFrame'>
Index: 625418 entries, 0 to 625559
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Anio           625418 non-null  int64
 1   Mes            625418 non-null  int64
 2   IDAeropuertoO  625418 non-null  string
 3   AeropuertoO    625418 non-null  object
 4   IDAeropuertoD  625418 non-null  string
 5   AeropuertoD    625418 non-null  object
 6   IDAerolinea    625418 non-null  string
 7   Aerolinea      625418 non-null  object
 8   VCargaC        625418 non-null  int64
 9   VCargaP        625418 non-null  int64
dtypes: int64(4), object(3), string(3)
memory usage: 52.5+ MB

In [ ]:
dfVC.head()

,Anio,Mes,IDAeropuertoO,AeropuertoO,IDAeropuertoD,AeropuertoD,IDAerolinea,Aerolinea,VCargaC,VCargaP
0,2008,5,13930,ORD,16217,YUL,19531,AC,3,0
1,2005,6,13303,MIA,14739,SDQ,20400,PT,0,21
2,2006,9,13204,MCO,12972,LHR,19540,BA,15,0
3,2004,8,13487,MSP,10292,AMS,19386,NW,479,0
4,2004,3,12478,JFK,16321,ZRH,19805,AA,687,0

--------------

Aeropuertos

In [ ]:
dfAP = pd.read_csv('/content/drive/MyDrive/NoCountry|S14-27/TablasTransformadas/Aeropuertos.csv')

In [ ]:
dfAP.IDAeropuerto = dfAP.IDAeropuerto.astype('string')

In [ ]:
dfVPC[dfVPC['AeropuertoO']=='PPG'][:1]

,Anio,Mes,IDAeropuertoO,AeropuertoO,IDAeropuertoD,AeropuertoD,IDAerolinea,Aerolinea,TablaOrigen,VPasajerosC,VPasajerosP,VCargaC,VCargaP,AsientosC,AsientosP,PasajerosC,PasajerosP
558,2004,11,14222,PPG,11671,FGI,19562,PH,"['VueloPasajeros', 'VueloCarga', 'Asientos', '...",130.0,0.0,5.0,0.0,2080.0,0.0,1432.0,0.0

In [ ]:
dfAP[dfAP['IDAeropuerto']=='14222']

     IDAeropuerto          NombreAeropuerto     Ciudad Pais
4054        14222   Pago Pago International  Pago Pago   TT

In [ ]:
# imputar
dfAP.loc[4054,'Pais'] = 'AS' # American Samoa

In [ ]:
dfVPC[dfVPC['AeropuertoO']=='GUM']['IDAeropuertoO'][:1]

0    12016
Name: IDAeropuertoO, dtype: string

In [ ]:
dfAP[dfAP['IDAeropuerto']=='12016']

     IDAeropuerto     NombreAeropuerto Ciudad Pais
1938        12016   Guam International   Guam   TT

In [ ]:
# imputar
dfAP.loc[1938,'Pais'] = 'GU' # Guam

In [ ]:
dfVPC[dfVPC['AeropuertoO']=='UAM']['IDAeropuertoO'][:1]

401    15422
Name: IDAeropuertoO, dtype: string

In [ ]:
dfAP[dfAP['IDAeropuerto']=='15422']

     IDAeropuerto NombreAeropuerto Ciudad Pais
5181        15422     Andersen AFB   Guam   TT

In [ ]:
# imputar
dfAP.loc[5181,'Pais'] = 'GU' # Guam

In [ ]:
dfVPC[dfVPC['AeropuertoO']=='SPN']['IDAeropuertoO'][:1]

191    14955
Name: IDAeropuertoO, dtype: string

In [ ]:
dfAP[dfAP['IDAeropuerto']=='14955']

     IDAeropuerto                        NombreAeropuerto  Ciudad Pais
4730        14955   Francisco C. Ada Saipan International  Saipan   TT

In [ ]:
# imputar
dfAP.loc[4730,'Pais'] = 'MP' # Guam

In [ ]:
dfVPC[dfVPC['AeropuertoO']=='AWK']['IDAeropuertoO'][:1]

13469    10439
Name: IDAeropuertoO, dtype: string

In [ ]:
dfAP[dfAP['IDAeropuerto']=='10439']

    IDAeropuerto       NombreAeropuerto       Ciudad Pais
414        10439   Wake Island Airfield  Wake Island   TT

In [ ]:
# imputar
dfAP.loc[414,'Pais'] = 'UM' # U.S. Minor Outlying Islands

In [ ]:
dfVPC[dfVPC['AeropuertoO']=='MDY']['IDAeropuertoO'][:1]

41943    13234
Name: IDAeropuertoO, dtype: string

In [ ]:
dfAP[dfAP['IDAeropuerto']=='13234']

     IDAeropuerto    NombreAeropuerto         Ciudad Pais
3100        13234   Sand Island Field  Midway Island   TT

In [ ]:
# imputar
dfAP.loc[3100,'Pais'] = 'UM' # U.S. Minor Outlying Islands

In [ ]:
dfAP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6669 entries, 0 to 6668
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   IDAeropuerto      6669 non-null   string
 1   NombreAeropuerto  6669 non-null   object
 2   Ciudad            6669 non-null   object
 3   Pais              6669 non-null   object
dtypes: object(3), string(1)
memory usage: 208.5+ KB

In [ ]:
dfAP.head()

  IDAeropuerto          NombreAeropuerto            Ciudad Pais
0        10001      Afognak Lake Airport      Afognak Lake   AK
1        10003   Bear Creek Mining Strip  Granite Mountain   AK
2        10004           Lik Mining Camp               Lik   AK
3        10005      Little Squaw Airport      Little Squaw   AK
4        10006              Kizhuyak Bay          Kizhuyak   AK

---------

Aerolineas

In [ ]:
dfAL = pd.read_csv('/content/drive/MyDrive/NoCountry|S14-27/TablasTransformadas/Aerolineas.csv')

In [ ]:
# imputar valores nulos
dfAL['Aerolinea'].fillna(value='NA', inplace=True)

In [ ]:
dfAL.rename({'Nombre':'NombreAerolinea'},axis=1, inplace=True)

In [ ]:
dfAL.IDAerolinea = dfAL.IDAerolinea.astype('string')
dfAL.TipoAerolinea = dfAL.TipoAerolinea.astype('string')

In [ ]:
dfAL.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1734 entries, 0 to 1733
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   IDAerolinea      1734 non-null   string
 1   Aerolinea        1734 non-null   object
 2   NombreAerolinea  1734 non-null   object
 3   TipoAerolinea    749 non-null    string
dtypes: object(2), string(2)
memory usage: 54.3+ KB

In [ ]:
dfAL.sample(5)

     IDAerolinea Aerolinea              NombreAerolinea TipoAerolinea
1595       20240       SNB                        Ccair          <NA>
136        20005        BR      Eva Airways Corporation           0.0
210        19553        LB  Lloyd Aereo Boliviano S. A.           0.0
1412       19814       ASU                Air South (1)          <NA>
1572       20159       XPA    Express Air d/b/a Sunrise          <NA>

------------

Estados USA

In [ ]:
dfST = pd.read_csv('/content/drive/MyDrive/NoCountry|S14-27/TablasTransformadas/EstadosUSA.csv')

In [ ]:
dfST.IDEstado = dfST.IDEstado.astype('string')
dfST.Estado = dfST.Estado.astype('string')

In [ ]:
# agregar estado
dfST.loc[len(dfST.index)] = ['UM','U.S. Minor Outlying Islands']

In [ ]:
dfST.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57 entries, 0 to 56
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   IDEstado  57 non-null     object
 1   Estado    57 non-null     object
dtypes: object(2)
memory usage: 1.3+ KB

In [ ]:
dfST.head()

  IDEstado         Estado
0       WA     Washington
1       NM     New Mexico
2       MA  Massachusetts
3       UT           Utah
4       IA           Iowa

---------

# GCP

------------

In [ ]:
!pip install google-cloud-bigquery

In [ ]:
!pip install pyarrow

In [ ]:
from google.cloud import bigquery

In [ ]:
# connection admin
key_path = '/content/cloudtest-400719-dce1ea0134cc.json'
client = bigquery.Client.from_service_account_json(key_path)

In [ ]:
# create table
table_id_flights = 'cloudtest-400719.NoCountry_s14_27.flights'

schema = []
table = bigquery.Table(table_id_flights, schema=schema)

table_flights = client.create_table(table)

In [ ]:
table_id_flightsPassengerCargo = 'cloudtest-400719.NoCountry_s14_27.flightsPassengerCargo'

schema = []
table = bigquery.Table(table_id_flightsPassengerCargo, schema=schema)

table_flights = client.create_table(table)

In [ ]:
table_id_flightsCargo = 'cloudtest-400719.NoCountry_s14_27.flightsCargo'

schema = []
table = bigquery.Table(table_id_flightsCargo, schema=schema)

table_flightsCargo = client.create_table(table)

In [ ]:
table_id_airports = 'cloudtest-400719.NoCountry_s14_27.airports'

schema = []
table = bigquery.Table(table_id_airports, schema=schema)

table_airports = client.create_table(table)

In [ ]:
table_id_airlines = 'cloudtest-400719.NoCountry_s14_27.airlines'

schema = []
table = bigquery.Table(table_id_airlines, schema=schema)

table_airlines = client.create_table(table)

In [ ]:
table_id_states = 'cloudtest-400719.NoCountry_s14_27.states'

schema = []
table = bigquery.Table(table_id_states, schema=schema)

table_states = client.create_table(table)

In [ ]:
# job load
job_config = bigquery.LoadJobConfig(
    schema = [
        bigquery.SchemaField('Anio', 'INTEGER'),
        bigquery.SchemaField('Mes', 'INTEGER'),
        bigquery.SchemaField('IDAeropuertoO', 'STRING'),
        bigquery.SchemaField('AeropuertoO', 'STRING'),
        bigquery.SchemaField('IDAeropuertoD', 'STRING'),
        bigquery.SchemaField('AeropuertoD', 'STRING'),
        bigquery.SchemaField('IDAerolinea', 'STRING'),
        bigquery.SchemaField('Aerolinea', 'STRING'),
        bigquery.SchemaField('TablaOrigen', 'STRING'),
        bigquery.SchemaField('VPasajerosC', 'INTEGER'),
        bigquery.SchemaField('VPasajerosP', 'INTEGER'),
        bigquery.SchemaField('VCargaC', 'INTEGER'),
        bigquery.SchemaField('VCargaP', 'INTEGER'),
        bigquery.SchemaField('AsientosC', 'INTEGER'),
        bigquery.SchemaField('AsientosP', 'INTEGER'),
        bigquery.SchemaField('PasajerosC', 'INTEGER'),
        bigquery.SchemaField('PasajerosP', 'INTEGER')
    ],
    write_disposition = 'WRITE_TRUNCATE' #'WRITE_APPEND'
)

job = client.load_table_from_dataframe(dfVPC, table_id_flightsPassengerCargo, job_config=job_config)

In [ ]:
job.result()

LoadJob<project=cloudtest-400719, location=us-west1, id=87bd5806-6345-44bf-8970-0bf266c08e83>

In [ ]:
job_config = bigquery.LoadJobConfig(
    schema = [
        bigquery.SchemaField('Anio', 'INTEGER'),
        bigquery.SchemaField('Mes', 'INTEGER'),
        bigquery.SchemaField('IDAeropuertoO', 'STRING'),
        bigquery.SchemaField('AeropuertoO', 'STRING'),
        bigquery.SchemaField('IDAeropuertoD', 'STRING'),
        bigquery.SchemaField('AeropuertoD', 'STRING'),
        bigquery.SchemaField('IDAerolinea', 'STRING'),
        bigquery.SchemaField('Aerolinea', 'STRING'),
        bigquery.SchemaField('TablaOrigen', 'STRING'),
        bigquery.SchemaField('VPasajerosC', 'INTEGER'),
        bigquery.SchemaField('VPasajerosP', 'INTEGER'),
        bigquery.SchemaField('AsientosC', 'INTEGER'),
        bigquery.SchemaField('AsientosP', 'INTEGER'),
        bigquery.SchemaField('PasajerosC', 'INTEGER'),
        bigquery.SchemaField('PasajerosP', 'INTEGER')
    ],
    write_disposition = 'WRITE_TRUNCATE' #'WRITE_APPEND'
)

job = client.load_table_from_dataframe(dfVP, table_id_flights, job_config=job_config)

In [ ]:
job_config = bigquery.LoadJobConfig(
    schema = [
        bigquery.SchemaField('Anio', 'INTEGER'),
        bigquery.SchemaField('Mes', 'INTEGER'),
        bigquery.SchemaField('IDAeropuertoO', 'STRING'),
        bigquery.SchemaField('AeropuertoO', 'STRING'),
        bigquery.SchemaField('IDAeropuertoD', 'STRING'),
        bigquery.SchemaField('AeropuertoD', 'STRING'),
        bigquery.SchemaField('IDAerolinea', 'STRING'),
        bigquery.SchemaField('Aerolinea', 'STRING'),
        bigquery.SchemaField('VCargaC', 'INTEGER'),
        bigquery.SchemaField('VCargaP', 'INTEGER'),
    ],
    write_disposition = 'WRITE_TRUNCATE' #'WRITE_APPEND'
)

job = client.load_table_from_dataframe(dfVC, table_id_flightsCargo, job_config=job_config)

In [ ]:
job_config = bigquery.LoadJobConfig(
    schema = [
        bigquery.SchemaField('IDAeropuerto', 'STRING'),
        bigquery.SchemaField('NombreAeropuerto', 'STRING'),
        bigquery.SchemaField('Ciudad', 'STRING'),
        bigquery.SchemaField('Pais', 'STRING')
    ],
    write_disposition = 'WRITE_TRUNCATE' # 'WRITE_APPEND'
)

job = client.load_table_from_dataframe(dfAP, table_id_airports, job_config=job_config)

In [ ]:
job_config = bigquery.LoadJobConfig(
    schema = [
        bigquery.SchemaField('IDAerolinea', 'STRING'),
        bigquery.SchemaField('Aerolinea', 'STRING'),
        bigquery.SchemaField('NombreAerolinea', 'STRING'),
        bigquery.SchemaField('TipoAerolinea', 'STRING')
    ],
    write_disposition = 'WRITE_TRUNCATE' # 'WRITE_APPEND'
)

job = client.load_table_from_dataframe(dfAL, table_id_airlines, job_config=job_config)

In [ ]:
job_config = bigquery.LoadJobConfig(
    schema = [
        bigquery.SchemaField('IDEstado', 'STRING'),
        bigquery.SchemaField('Estado', 'STRING'),
    ],
    write_disposition = 'WRITE_TRUNCATE' # 'WRITE_APPEND'
)

job = client.load_table_from_dataframe(dfST, table_id_states, job_config=job_config)

-----------

Query fights cargo

In [ ]:
query = """
  SELECT
    f.Anio,
    f.Mes,
    f.AeropuertoO,
    a1.Ciudad as CiudadO,
    s.Estado as EstadoO,
    f.AeropuertoD,
    a2.Ciudad as CiudadD,
    a2.Pais as PaisD,
    f.Aerolinea,
    a.NombreAerolinea,
    a.TipoAerolinea,
    SUM(f.VCargaC) as VCargaC,
    SUM(f.VCargaP) as VCargaP
  FROM
    cloudtest-400719.NoCountry_s14_27.flightsCargo f
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a1 ON f.IDAeropuertoO = a1.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a2 ON f.IDAeropuertoD = a2.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airlines a ON f.IDAerolinea = a.IDAerolinea
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.states s ON a1.Pais = s.IDEstado
  GROUP BY
    f.Anio,
    f.Mes,
    f.AeropuertoO,
    a1.Ciudad,
    s.Estado,
    f.AeropuertoD,
    a2.Ciudad,
    a2.Pais,
    f.Aerolinea,
    a.NombreAerolinea,
    a.TipoAerolinea
  HAVING anio > 2018
"""

In [ ]:
job = client.query(query)
dfFC = job.to_dataframe()

In [ ]:
dfFC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85128 entries, 0 to 85127
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Anio             85128 non-null  Int64
 1   Mes              85128 non-null  Int64
 2   AeropuertoO      85128 non-null  object
 3   CiudadO          85128 non-null  object
 4   EstadoO          85128 non-null  object
 5   AeropuertoD      85128 non-null  object
 6   CiudadD          85128 non-null  object
 7   PaisD            85128 non-null  object
 8   Aerolinea        85128 non-null  object
 9   NombreAerolinea  85128 non-null  object
 10  TipoAerolinea    85128 non-null  object
 11  VCargaC          85128 non-null  Int64
 12  VCargaP          85128 non-null  Int64
dtypes: Int64(4), object(9)
memory usage: 8.8+ MB

In [ ]:
dfFC.head()

,Anio,Mes,AeropuertoO,CiudadO,EstadoO,AeropuertoD,CiudadD,PaisD,Aerolinea,NombreAerolinea,TipoAerolinea,VCargaC,VCargaP
0,2021,8,RFD,Rockford,Illinois,AAN,Al Ain,United Arab Emirates,N8,National Air Cargo Group Inc d/ba National Air...,1.0,0,21
1,2023,5,GSP,Greer,South Carolina,ABJ,Abidjan,Cote d'Ivoire,CC,Air Atlanta Icelandic,0.0,0,91
2,2022,4,MIA,Miami,Florida,ACA,Acapulco,Mexico,AM,Aeromexico,0.0,1,0
3,2022,8,MIA,Miami,Florida,ACA,Acapulco,Mexico,M6,Amerijet International,1.0,12,0
4,2022,11,ANC,Anchorage,Alaska,ACA,Acapulco,Mexico,M7,Aerotransportes Mas De Crga,0.0,368,0

In [ ]:
dfFC.isna().sum()

Anio               0
Mes                0
AeropuertoO        0
CiudadO            0
EstadoO            0
AeropuertoD        0
CiudadD            0
PaisD              0
Aerolinea          0
NombreAerolinea    0
TipoAerolinea      0
VCargaC            0
VCargaP            0
dtype: int64

-------------

Query flights passengers

In [ ]:
query = """
  SELECT
    f.Anio,
    f.Mes,
    f.AeropuertoO,
    a1.Ciudad as CiudadO,
    s.Estado as EstadoO,
    f.AeropuertoD,
    a2.Ciudad as CiudadD,
    a2.Pais as PaisD,
    f.Aerolinea,
    a.NombreAerolinea,
    a.TipoAerolinea,
    SUM(f.VPasajerosC) as VPasajerosC,
    SUM(f.VPasajerosP) as VPasajerosP,
    SUM(f.AsientosC) as AsientosC,
    SUM(f.AsientosP) as AsientosP,
    SUM(f.PasajerosC) as PasajerosC,
    SUM(f.PasajerosP) as PasajerosP
  FROM
    cloudtest-400719.NoCountry_s14_27.flights f
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a1 ON f.IDAeropuertoO = a1.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a2 ON f.IDAeropuertoD = a2.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airlines a ON f.IDAerolinea = a.IDAerolinea
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.states s ON a1.Pais = s.IDEstado
  GROUP BY
    f.Anio,
    f.Mes,
    f.AeropuertoO,
    a1.Ciudad,
    s.Estado,
    f.AeropuertoD,
    a2.Ciudad,
    a2.Pais,
    f.Aerolinea,
    a.NombreAerolinea,
    a.TipoAerolinea
  HAVING anio > 2018
"""

In [ ]:
job = client.query(query)
dfFP = job.to_dataframe()

In [ ]:
dfFP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168705 entries, 0 to 168704
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Anio             168705 non-null  Int64
 1   Mes              168705 non-null  Int64
 2   AeropuertoO      168705 non-null  object
 3   CiudadO          168705 non-null  object
 4   EstadoO          168705 non-null  object
 5   AeropuertoD      168705 non-null  object
 6   CiudadD          168705 non-null  object
 7   PaisD            168705 non-null  object
 8   Aerolinea        168705 non-null  object
 9   NombreAerolinea  168705 non-null  object
 10  TipoAerolinea    168705 non-null  object
 11  VPasajerosC      168700 non-null  Int64
 12  VPasajerosP      168700 non-null  Int64
 13  AsientosC        128700 non-null  Int64
 14  AsientosP        128700 non-null  Int64
 15  PasajerosC       123735 non-null  Int64
 16  PasajerosP       123735 non-null  Int64
dtypes: Int64(8), object(9)
memory usage: 23.2+ MB

In [ ]:
dfFP.head()

,Anio,Mes,AeropuertoO,CiudadO,EstadoO,AeropuertoD,CiudadD,PaisD,Aerolinea,NombreAerolinea,TipoAerolinea,VPasajerosC,VPasajerosP,AsientosC,AsientosP,PasajerosC,PasajerosP
0,2021,7,PIT,Pittsburgh,Pennsylvania,PUJ,Punta Cana,Dominican Republic,G4,Allegiant Air,1.0,0,10,0,1560,0,1495
1,2021,7,PIT,Pittsburgh,Pennsylvania,YQA,Muskoka,Canada,13Q,Chartright Air Inc.,0.0,0,1,0,8,0,1
2,2021,7,PIT,Pittsburgh,Pennsylvania,YYZ,Toronto,Canada,13Q,Chartright Air Inc.,0.0,0,4,0,24,0,5
3,2021,7,PSM,Portsmouth,New Hampshire,BCN,Barcelona,Spain,3FQ,"Western Air Charter, Inc. d/b/a Jet Edge",1.0,0,1,0,16,0,4
4,2021,7,PSM,Portsmouth,New Hampshire,BDA,Hamilton,Bermuda,3FQ,"Western Air Charter, Inc. d/b/a Jet Edge",1.0,0,1,0,15,<NA>,<NA>

In [ ]:
dfFP.isna().sum()

Anio                   0
Mes                    0
AeropuertoO            0
CiudadO                0
EstadoO                0
AeropuertoD            0
CiudadD                0
PaisD                  0
Aerolinea              0
NombreAerolinea        0
TipoAerolinea          0
VPasajerosC            5
VPasajerosP            5
AsientosC          40005
AsientosP          40005
PasajerosC         44970
PasajerosP         44970
dtype: int64

-------------

Query flights passengers cargo

In [ ]:
query = """
  SELECT
    f.Anio,
    f.Mes,
    f.AeropuertoO,
    a1.Ciudad as CiudadO,
    s.Estado as EstadoO,
    f.AeropuertoD,
    a2.Ciudad as CiudadD,
    a2.Pais as PaisD,
    f.Aerolinea,
    a.NombreAerolinea,
    a.TipoAerolinea,
    SUM(f.VPasajerosC) as VPasajerosC,
    SUM(f.VPasajerosP) as VPasajerosP,
    SUM(f.VCargaC) as VCargaC,
    SUM(f.VCargaP) as VCargaP,
    SUM(f.AsientosC) as AsientosC,
    SUM(f.AsientosP) as AsientosP,
    SUM(f.PasajerosC) as PasajerosC,
    SUM(f.PasajerosP) as PasajerosP
  FROM
    cloudtest-400719.NoCountry_s14_27.flightsPassengerCargo f
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a1 ON f.IDAeropuertoO = a1.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a2 ON f.IDAeropuertoD = a2.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airlines a ON f.IDAerolinea = a.IDAerolinea
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.states s ON a1.Pais = s.IDEstado
  GROUP BY
    f.Anio,
    f.Mes,
    f.AeropuertoO,
    a1.Ciudad,
    s.Estado,
    f.AeropuertoD,
    a2.Ciudad,
    a2.Pais,
    f.Aerolinea,
    a.NombreAerolinea,
    a.TipoAerolinea
  HAVING anio > 2018
"""

In [ ]:
job = client.query(query)
dfFPC = job.to_dataframe()

In [ ]:
dfFPC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168705 entries, 0 to 168704
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Anio             168705 non-null  Int64
 1   Mes              168705 non-null  Int64
 2   AeropuertoO      168705 non-null  object
 3   CiudadO          168705 non-null  object
 4   EstadoO          168705 non-null  object
 5   AeropuertoD      168705 non-null  object
 6   CiudadD          168705 non-null  object
 7   PaisD            168705 non-null  object
 8   Aerolinea        168705 non-null  object
 9   NombreAerolinea  168705 non-null  object
 10  TipoAerolinea    168705 non-null  object
 11  VPasajerosC      168700 non-null  Int64
 12  VPasajerosP      168700 non-null  Int64
 13  VCargaC          85128 non-null   Int64
 14  VCargaP          85128 non-null   Int64
 15  AsientosC        128700 non-null  Int64
 16  AsientosP        128700 non-null  Int64
 17  PasajerosC       123735 non-null  Int64
 18  PasajerosP       123735 non-null  Int64
dtypes: Int64(10), object(9)
memory usage: 26.1+ MB

In [ ]:
dfFPC.head()

,Anio,Mes,AeropuertoO,CiudadO,EstadoO,AeropuertoD,CiudadD,PaisD,Aerolinea,NombreAerolinea,TipoAerolinea,VPasajerosC,VPasajerosP,VCargaC,VCargaP,AsientosC,AsientosP,PasajerosC,PasajerosP
0,2021,8,HSV,Huntsville,Alabama,VCP,Sao Paulo,Brazil,5Y,Atlas Air Inc.,1.0,0,3,0,111,<NA>,<NA>,0,2
1,2021,8,RFD,Rockford,Illinois,ICN,Seoul,South Korea,5Y,Atlas Air Inc.,1.0,0,2,0,2,0,8,<NA>,<NA>
2,2021,8,STL,St. Louis,Missouri,VCP,Sao Paulo,Brazil,5Y,Atlas Air Inc.,1.0,0,1,0,39,<NA>,<NA>,0,3
3,2021,10,HSV,Huntsville,Alabama,VCP,Sao Paulo,Brazil,5Y,Atlas Air Inc.,1.0,0,2,0,62,<NA>,<NA>,0,2
4,2021,9,GSP,Greer,South Carolina,LGW,London,United Kingdom,BY,Britannia Airways Ltd.,0.0,0,8,0,167,0,2760,<NA>,<NA>

In [ ]:
dfFPC.isna().sum()

Anio                   0
Mes                    0
AeropuertoO            0
CiudadO                0
EstadoO                0
AeropuertoD            0
CiudadD                0
PaisD                  0
Aerolinea              0
NombreAerolinea        0
TipoAerolinea          0
VPasajerosC            5
VPasajerosP            5
VCargaC            83577
VCargaP            83577
AsientosC          40005
AsientosP          40005
PasajerosC         44970
PasajerosP         44970
dtype: int64

------------

Query AeropuertoOrigen MIA, Aerolinea AA

In [ ]:
query = """
  SELECT
    f.Anio,
    f.Mes,
    f.AeropuertoO as AeropuertoOrigen,
    a1.NombreAeropuerto as AeropuertoOrigenNombre,
    a1.Ciudad as CiudadOrigen,
    s.Estado as EstadoOrigen,
    f.AeropuertoD as AeropuertoDestino,
    a2.NombreAeropuerto as AeropuertoDestinoNombre,
    a2.Ciudad as CiudadDestino,
    a2.Pais as PaisDestino,
    f.Aerolinea,
    a.NombreAerolinea as AerolineaNombre,
    SUM(f.VPasajerosC) as VPasajerosC,
    SUM(f.VPasajerosP) as VPasajerosP,
    SUM(f.AsientosC) as AsientosC,
    SUM(f.AsientosP) as AsientosP,
    SUM(f.PasajerosC) as PasajerosC,
    SUM(f.PasajerosP) as PasajerosP
  FROM
    cloudtest-400719.NoCountry_s14_27.flights f
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a1 ON f.IDAeropuertoO = a1.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a2 ON f.IDAeropuertoD = a2.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airlines a ON f.IDAerolinea = a.IDAerolinea
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.states s ON a1.Pais = s.IDEstado
  GROUP BY
    f.Anio,
    f.Mes,
    f.AeropuertoO,
    a1.NombreAeropuerto,
    a1.Ciudad,
    s.Estado,
    f.AeropuertoD,
    a2.NombreAeropuerto,
    a2.Ciudad,
    a2.Pais,
    f.Aerolinea,
    a.NombreAerolinea
  HAVING f.AeropuertoO = 'MIA' and f.Aerolinea = 'AA'
"""

In [ ]:
job = client.query(query)
df = job.to_dataframe()

PermissionDenied: 403 request failed: the user does not have 'bigquery.readsessions.create' permission for 'projects/cloudtest-400719'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20656 entries, 0 to 20655
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Anio                     20656 non-null  Int64
 1   Mes                      20656 non-null  Int64
 2   AeropuertoOrigen         20656 non-null  object
 3   AeropuertoOrigenNombre   20656 non-null  object
 4   CiudadOrigen             20656 non-null  object
 5   EstadoOrigen             20656 non-null  object
 6   AeropuertoDestino        20656 non-null  object
 7   AeropuertoDestinoNombre  20656 non-null  object
 8   CiudadDestino            20656 non-null  object
 9   PaisDestino              20656 non-null  object
 10  Aerolinea                20656 non-null  object
 11  AerolineaNombre          20656 non-null  object
 12  VPasajerosC              20656 non-null  Int64
 13  VPasajerosP              20656 non-null  Int64
 14  AsientosC                20638 non-null  Int64
 15  AsientosP                20638 non-null  Int64
 16  PasajerosC               20623 non-null  Int64
 17  PasajerosP               20623 non-null  Int64
dtypes: Int64(8), object(10)
memory usage: 3.0+ MB

In [ ]:
df.sample(10)

,Anio,Mes,AeropuertoOrigen,AeropuertoOrigenNombre,CiudadOrigen,EstadoOrigen,AeropuertoDestino,AeropuertoDestinoNombre,CiudadDestino,PaisDestino,Aerolinea,AerolineaNombre,VPasajerosC,VPasajerosP,AsientosC,AsientosP,PasajerosC,PasajerosP
5117,2017,2,MIA,Miami International,Miami,Florida,LPB,El Alto International,La Paz,Bolivia,AA,American Airlines Inc.,28,0,4770,0,4262,0
14612,2021,11,MIA,Miami International,Miami,Florida,SJO,Juan Santamaria International,San Jose,Costa Rica,AA,American Airlines Inc.,172,0,29584,0,27486,0
19130,2010,3,MIA,Miami International,Miami,Florida,GYE,Jose Joaquin de Olmedo International,Guayaquil,Ecuador,AA,American Airlines Inc.,62,0,13950,0,11748,0
7440,2008,12,MIA,Miami International,Miami,Florida,TGU,Toncontin International,Tegucigalpa,Honduras,AA,American Airlines Inc.,62,0,11656,0,8174,0
19815,2004,2,MIA,Miami International,Miami,Florida,GIG,Galeao Antonio Carlos Jobim International,Rio de Janeiro,Brazil,AA,American Airlines Inc.,100,0,20672,0,14168,0
4552,2011,7,MIA,Miami International,Miami,Florida,CUN,Cancun International,Cancun,Mexico,AA,American Airlines Inc.,305,0,48752,0,43498,0
10743,2021,11,MIA,Miami International,Miami,Florida,LIR,Daniel Oduber International,Liberia,Costa Rica,AA,American Airlines Inc.,56,0,7468,0,6835,0
11686,2020,12,MIA,Miami International,Miami,Florida,AUA,Reina Beatrix International,Aruba,Aruba,AA,American Airlines Inc.,107,0,19032,0,10552,0
13976,2002,1,MIA,Miami International,Miami,Florida,SDQ,De Las Americas International,Santo Domingo,Dominican Republic,AA,American Airlines Inc.,250,0,52918,0,34773,0
10522,2011,11,MIA,Miami International,Miami,Florida,LRM,Casa de Campo International,La Romana,Dominican Republic,AA,American Airlines Inc.,8,0,1208,0,641,0

In [ ]:
df.isna().sum()

Anio                        0
Mes                         0
AeropuertoOrigen            0
AeropuertoOrigenNombre      0
CiudadOrigen                0
EstadoOrigen                0
AeropuertoDestino           0
AeropuertoDestinoNombre     0
CiudadDestino               0
PaisDestino                 0
Aerolinea                   0
AerolineaNombre             0
VPasajerosC                 0
VPasajerosP                 0
AsientosC                  18
AsientosP                  18
PasajerosC                 33
PasajerosP                 33
dtype: int64

------------

Access NoCountry Team

In [ ]:
# connection viewer
key_path = '/content/cloudtest-400719-b58d2805d444.json'
location = 'us-west1'
client = bigquery.Client.from_service_account_json(key_path, location=location)

In [ ]:
job = client.get_job('b9c69a32-2ed8-4791-bfb6-caba8c4081b0')
#print(job.query)

In [ ]:
dfFPC = job.to_dataframe()

In [ ]:
dfFPC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168705 entries, 0 to 168704
Data columns (total 19 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Anio             168705 non-null  Int64
 1   Mes              168705 non-null  Int64
 2   AeropuertoO      168705 non-null  object
 3   CiudadO          168705 non-null  object
 4   EstadoO          168705 non-null  object
 5   AeropuertoD      168705 non-null  object
 6   CiudadD          168705 non-null  object
 7   PaisD            168705 non-null  object
 8   Aerolinea        168705 non-null  object
 9   NombreAerolinea  168705 non-null  object
 10  TipoAerolinea    168705 non-null  object
 11  VPasajerosC      168700 non-null  Int64
 12  VPasajerosP      168700 non-null  Int64
 13  VCargaC          85128 non-null   Int64
 14  VCargaP          85128 non-null   Int64
 15  AsientosC        128700 non-null  Int64
 16  AsientosP        128700 non-null  Int64
 17  PasajerosC       123735 non-null  Int64
 18  PasajerosP       123735 non-null  Int64
dtypes: Int64(10), object(9)
memory usage: 26.1+ MB

In [ ]:
dfFPC.head()

,Anio,Mes,AeropuertoO,CiudadO,EstadoO,AeropuertoD,CiudadD,PaisD,Aerolinea,NombreAerolinea,TipoAerolinea,VPasajerosC,VPasajerosP,VCargaC,VCargaP,AsientosC,AsientosP,PasajerosC,PasajerosP
0,2021,8,HSV,Huntsville,Alabama,VCP,Sao Paulo,Brazil,5Y,Atlas Air Inc.,1.0,0,3,0,111,<NA>,<NA>,0,2
1,2021,8,RFD,Rockford,Illinois,ICN,Seoul,South Korea,5Y,Atlas Air Inc.,1.0,0,2,0,2,0,8,<NA>,<NA>
2,2021,8,STL,St. Louis,Missouri,VCP,Sao Paulo,Brazil,5Y,Atlas Air Inc.,1.0,0,1,0,39,<NA>,<NA>,0,3
3,2021,10,HSV,Huntsville,Alabama,VCP,Sao Paulo,Brazil,5Y,Atlas Air Inc.,1.0,0,2,0,62,<NA>,<NA>,0,2
4,2021,9,GSP,Greer,South Carolina,LGW,London,United Kingdom,BY,Britannia Airways Ltd.,0.0,0,8,0,167,0,2760,<NA>,<NA>

-----

In [ ]:
job = client.get_job('bab91cee-07aa-4e07-9eb8-1192fa229425')
#print(job.query)

In [ ]:
dfFP = job.to_dataframe()

In [ ]:
dfFP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168705 entries, 0 to 168704
Data columns (total 17 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Anio             168705 non-null  Int64
 1   Mes              168705 non-null  Int64
 2   AeropuertoO      168705 non-null  object
 3   CiudadO          168705 non-null  object
 4   EstadoO          168705 non-null  object
 5   AeropuertoD      168705 non-null  object
 6   CiudadD          168705 non-null  object
 7   PaisD            168705 non-null  object
 8   Aerolinea        168705 non-null  object
 9   NombreAerolinea  168705 non-null  object
 10  TipoAerolinea    168705 non-null  object
 11  VPasajerosC      168700 non-null  Int64
 12  VPasajerosP      168700 non-null  Int64
 13  AsientosC        128700 non-null  Int64
 14  AsientosP        128700 non-null  Int64
 15  PasajerosC       123735 non-null  Int64
 16  PasajerosP       123735 non-null  Int64
dtypes: Int64(8), object(9)
memory usage: 23.2+ MB

In [ ]:
dfFP.head()

,Anio,Mes,AeropuertoO,CiudadO,EstadoO,AeropuertoD,CiudadD,PaisD,Aerolinea,NombreAerolinea,TipoAerolinea,VPasajerosC,VPasajerosP,AsientosC,AsientosP,PasajerosC,PasajerosP
0,2021,7,PIT,Pittsburgh,Pennsylvania,PUJ,Punta Cana,Dominican Republic,G4,Allegiant Air,1.0,0,10,0,1560,0,1495
1,2021,7,PIT,Pittsburgh,Pennsylvania,YQA,Muskoka,Canada,13Q,Chartright Air Inc.,0.0,0,1,0,8,0,1
2,2021,7,PIT,Pittsburgh,Pennsylvania,YYZ,Toronto,Canada,13Q,Chartright Air Inc.,0.0,0,4,0,24,0,5
3,2021,7,PSM,Portsmouth,New Hampshire,BCN,Barcelona,Spain,3FQ,"Western Air Charter, Inc. d/b/a Jet Edge",1.0,0,1,0,16,0,4
4,2021,7,PSM,Portsmouth,New Hampshire,BDA,Hamilton,Bermuda,3FQ,"Western Air Charter, Inc. d/b/a Jet Edge",1.0,0,1,0,15,<NA>,<NA>

-----------

In [ ]:
job = client.get_job('1de87cc3-51c4-43f0-9161-11c36438ae7c')
#print(job.query)

In [ ]:
dfFC = job.to_dataframe()

In [ ]:
dfFC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85128 entries, 0 to 85127
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Anio             85128 non-null  Int64
 1   Mes              85128 non-null  Int64
 2   AeropuertoO      85128 non-null  object
 3   CiudadO          85128 non-null  object
 4   EstadoO          85128 non-null  object
 5   AeropuertoD      85128 non-null  object
 6   CiudadD          85128 non-null  object
 7   PaisD            85128 non-null  object
 8   Aerolinea        85128 non-null  object
 9   NombreAerolinea  85128 non-null  object
 10  TipoAerolinea    85128 non-null  object
 11  VCargaC          85128 non-null  Int64
 12  VCargaP          85128 non-null  Int64
dtypes: Int64(4), object(9)
memory usage: 8.8+ MB

In [ ]:
dfFC.head()

,Anio,Mes,AeropuertoO,CiudadO,EstadoO,AeropuertoD,CiudadD,PaisD,Aerolinea,NombreAerolinea,TipoAerolinea,VCargaC,VCargaP
0,2021,8,RFD,Rockford,Illinois,AAN,Al Ain,United Arab Emirates,N8,National Air Cargo Group Inc d/ba National Air...,1.0,0,21
1,2023,5,GSP,Greer,South Carolina,ABJ,Abidjan,Cote d'Ivoire,CC,Air Atlanta Icelandic,0.0,0,91
2,2022,4,MIA,Miami,Florida,ACA,Acapulco,Mexico,AM,Aeromexico,0.0,1,0
3,2022,8,MIA,Miami,Florida,ACA,Acapulco,Mexico,M6,Amerijet International,1.0,12,0
4,2022,11,ANC,Anchorage,Alaska,ACA,Acapulco,Mexico,M7,Aerotransportes Mas De Crga,0.0,368,0

-----------

In [ ]:
job = client.get_job('10f56db6-03e7-48b5-9709-7aaa6f1dee51')
print(job.query)

  SELECT
    f.Anio,
    f.Mes,
    f.AeropuertoO as AeropuertoOrigen,
    a1.NombreAeropuerto as AeropuertoOrigenNombre,
    a1.Ciudad as CiudadOrigen,
    s.Estado as EstadoOrigen,
    f.AeropuertoD as AeropuertoDestino,
    a2.NombreAeropuerto as AeropuertoDestinoNombre,
    a2.Ciudad as CiudadDestino,
    a2.Pais as PaisDestino,
    f.Aerolinea,
    a.NombreAerolinea as AerolineaNombre,
    SUM(f.VPasajerosC) as VPasajerosC,
    SUM(f.VPasajerosP) as VPasajerosP,
    SUM(f.AsientosC) as AsientosC,
    SUM(f.AsientosP) as AsientosP,
    SUM(f.PasajerosC) as PasajerosC,
    SUM(f.PasajerosP) as PasajerosP
  FROM
    cloudtest-400719.NoCountry_s14_27.flights f
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a1 ON f.IDAeropuertoO = a1.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airports a2 ON f.IDAeropuertoD = a2.IDAeropuerto
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.airlines a ON f.IDAerolinea = a.IDAerolinea
  LEFT OUTER JOIN
    cloudtest-400719.NoCountry_s14_27.states s ON a1.Pais = s.IDEstado
  GROUP BY
    f.Anio,
    f.Mes,
    f.AeropuertoO,
    a1.NombreAeropuerto,
    a1.Ciudad,
    s.Estado,
    f.AeropuertoD,
    a2.NombreAeropuerto,
    a2.Ciudad,
    a2.Pais,
    f.Aerolinea,
    a.NombreAerolinea
  HAVING f.AeropuertoO = 'MIA' and f.Aerolinea = 'AA'

In [ ]:
df = job.to_dataframe()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20656 entries, 0 to 20655
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Anio                     20656 non-null  Int64
 1   Mes                      20656 non-null  Int64
 2   AeropuertoOrigen         20656 non-null  object
 3   AeropuertoOrigenNombre   20656 non-null  object
 4   CiudadOrigen             20656 non-null  object
 5   EstadoOrigen             20656 non-null  object
 6   AeropuertoDestino        20656 non-null  object
 7   AeropuertoDestinoNombre  20656 non-null  object
 8   CiudadDestino            20656 non-null  object
 9   PaisDestino              20656 non-null  object
 10  Aerolinea                20656 non-null  object
 11  AerolineaNombre          20656 non-null  object
 12  VPasajerosC              20656 non-null  Int64
 13  VPasajerosP              20656 non-null  Int64
 14  AsientosC                20638 non-null  Int64
 15  AsientosP                20638 non-null  Int64
 16  PasajerosC               20623 non-null  Int64
 17  PasajerosP               20623 non-null  Int64
dtypes: Int64(8), object(10)
memory usage: 3.0+ MB

In [ ]:
df.shape

(20656, 18)

In [ ]:
df.sample(10)

,Anio,Mes,AeropuertoOrigen,AeropuertoOrigenNombre,CiudadOrigen,EstadoOrigen,AeropuertoDestino,AeropuertoDestinoNombre,CiudadDestino,PaisDestino,Aerolinea,AerolineaNombre,VPasajerosC,VPasajerosP,AsientosC,AsientosP,PasajerosC,PasajerosP
6156,2010,10,MIA,Miami International,Miami,Florida,ANU,V C Bird International,St. Johns,Antigua and Barbuda,AA,American Airlines Inc.,63,0,9324,0,7449,0
2914,2014,5,MIA,Miami International,Miami,Florida,BCN,Barcelona Airport,Barcelona,Spain,AA,American Airlines Inc.,62,0,13142,0,11350,0
4897,2003,3,MIA,Miami International,Miami,Florida,LPB,El Alto International,La Paz,Bolivia,AA,American Airlines Inc.,30,0,5220,0,2926,0
10114,2006,6,MIA,Miami International,Miami,Florida,GCM,Owen Roberts International,Grand Cayman,Cayman Islands,AA,American Airlines Inc.,103,0,15244,0,12081,0
5146,2004,9,MIA,Miami International,Miami,Florida,PTY,Tocumen International,Panama City,Panama,AA,American Airlines Inc.,108,0,20304,0,9846,0
17210,2008,6,MIA,Miami International,Miami,Florida,BZE,Philip S. W. Goldson International,Belize City,Belize,AA,American Airlines Inc.,114,0,16872,0,10676,0
10196,1990,2,MIA,Miami International,Miami,Florida,GCM,Owen Roberts International,Grand Cayman,Cayman Islands,AA,American Airlines Inc.,56,0,8400,0,6534,0
13111,2010,8,MIA,Miami International,Miami,Florida,PAP,Port Au Prince International,Port-au-Prince,Haiti,AA,American Airlines Inc.,231,0,46352,0,42053,0
17502,2001,7,MIA,Miami International,Miami,Florida,SCL,Arturo Merino Benitez International,Santiago,Chile,AA,American Airlines Inc.,61,0,11389,0,7606,0
546,1991,6,MIA,Miami International,Miami,Florida,ASU,Silvio Pettirossi International,Asuncion,Paraguay,AA,American Airlines Inc.,2,0,346,0,269,0